remove unneeded dns extension driver that breaks floats
Removing the above fixes the following error:

2019-05-23 15:22:18.507 860995 ERROR neutron.api.v2.resource     return f(*dup_args, **dup_kwargs)
2019-05-23 15:22:18.507 860995 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/db/l3_db.py", line 1406, in create_floatingip
2019-05-23 15:22:18.507 860995 ERROR neutron.api.v2.resource     return self._create_floatingip(context, floatingip, initial_status)
2019-05-23 15:22:18.507 860995 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/db/l3_db.py", line 1373, in _create_floatingip
2019-05-23 15:22:18.507 860995 ERROR neutron.api.v2.resource     dns_data = self._process_dns_floatingip_create_precommit(
2019-05-23 15:22:18.507 860995 ERROR neutron.api.v2.resource AttributeError: 'CalicoPlugin' object has no attribute '_process_dns_floatingip_create_precommit'
2019-05-23 15:22:18.507 860995 ERROR neutron.api.v2.resource